version: '3.1'
services:
  core:
    image: hesabfun/core:latest
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "6080:80"
    environment:
      E_SERVICES_POSTGRES_DB: "${POSTGRES_DB}"
      E_SERVICES_POSTGRES_USER: "${POSTGRES_USER}"
      E_SERVICES_POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      E_SERVICES_POSTGRES_HOST: postgres
      E_SERVICES_REDIS_ADDRESS: redis
      E_SERVICES_REDIS_PASSWORD: "${REDIS_PASSWORD}"

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  redis:
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./volumes/redis:/data

  ui:
    image: hesabfun/ui:latest
    restart: always
    ports:
      - "6081:80"

  template:
    image: hesabfun/template:latest
    restart: always
    command: bash -c "npm run build && live-server public --port=80"
    ports:
      - "6082:80"