version: '3.1'
services:
  core:
    image: hesabfun/core:latest
    restart: always
    depends_on:
      - db
    ports:
      - "6081:80"
    env_file:
      - core.env
    secrets:
      - private_key
      - public_key
    environment:
      MYSQL_DATABASE: hesabfun
      MYSQL_ADDRESS: db
      MYSQL_USERNAME: root
      MYSQL_PORT: 3306
      PORT: 80
      JWT_RSA_PRIVATE_KEY_PATH: /run/secrets/private_key
      JWT_RSA_PUBLIC_KEY_PATH: /run/secrets/public_key

  db:
    image: mariadb
    restart: always
    env_file:
      - db.env
    environment:
      MYSQL_DATABASE: hesabfun
    volumes:
      - /hesabfun/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "6083:80"
    environment:
      PMA_HOST: db

  docs:
    image: hesabfun/docs:latest
    restart: always
    ports:
      - "6082:80"

  ui:
    image: hesabfun/ui:latest
    restart: always
    ports:
      - "6080:80"

secrets:
  private_key:
    file: ./private.pem
  public_key:
      file: ./public.pem